<?php

namespace Sdz\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
  public function myFindAll()
    {
        $queryBuilder = $this->createQueryBuilder('a');

        // Méthode équivalente, mais plus longue :
        $queryBuilder = $this->_em
            ->createQueryBuilder()
            ->select('a')
            ->from($this->_entityName, 'a');

        // Dans un repository, $this->_entityName est le namespace de l'entité gérée
        // Ici il vaut donc Sdz\BlogBundle\Entity\Article

        // On a fini de construire notre requête

        // On récupère la Query à partir de QueryBuilder
        $query = $queryBuilder->getQuery();

        // On récupère les résultats à partir de la query
        $resultats = $query->getResult();

        // On retourne ces résultats
        return $resultats;

    }
    
    public function myFindOne($id)
    {
        // On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
        $qb = $this->_em->createQueryBuilder();

        $qb->select('a')
           ->from('SdzBlogBundle:Article', 'a')
           ->where('a.id = :id')
           ->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }
}
