# src/Sdz/BlogBundle/Resources/config/routing.yml

sdzblog_accueil:
    path: /{page}
    defaults: { _controller: SdzBlogBundle:Blog:index, page: 1 }
    requirements:
        page: \d*
    
sdzblog_voir:
    path: /article/{id}
    defaults: { _controller: SdzBlogBundle:Blog:voir }

sdzblog_voir_slug:
    path: /{annee}/{slug}.{format}
    defaults: { _controller: SdzBlogBundle:Blog:voirSlug, format: html }
    requirements:
        annee: \d{4}
        format: html|xml
    
sdzblog_ajouter:
    path: /ajouter
    defaults: { _controller: SdzBlogBundle:Blog:ajouter }

sdzblog_modifier:
    path: /modifier/{id}
    defaults: { _controller: SdzBlogBundle:Blog:modifier }

sdzblog_supprimer:
    path: /supprimer/{id}
    defaults: { _controller: SdzBlogBundle:Blog:supprimer }
